### ISSUE TITLE
Small refactoring needed IdleGame.cs

### ISSUE THREAD

**Issue by vcosmin2701** [MircaSalvatorul/ClickerGame#1]
1.Create method to output the label
`clickup2Text.text = "Click Upgrade 2\nCost:" + clickUpgrade2Cost.ToString("F2") + "\nPower +5\nLevel: " + clickUpgrade2Level;`
2. Get rid of 'magical values'

**Comment by MircaSalvatorul** [comment]
ok. so, there are a few problems with this. if i create a method for both types of upgrades, i would need to standardise all their variables (which actually sounds doable, now that i think of it). but i am concerned that making methods outside of the update method will slow down the process. 
Although i will start work on this

**Comment by vcosmin2701** [comment]
You just need to create a method that takes as parameter the variable you want and output the label formatted. It should not affect the performance😀
